In [ ]:
from pyvis.network import Network

def add_param(central, node_value, edge_value):
    global corresp
    global count 
    
    if node_value not in corresp:
        count += 1
        corresp[node_value] = count
        
        net.add_node(
            count,
            label=node_value,
            color="purple",
            size=20
        )
        curcount = count
    
    curcount = corresp[node_value]
    net.add_edge(central, curcount, label=edge_value)

# Création du graphe
net = Network(
    height="800px",
    width="100%",
    directed=True
)

for node in [1,2,3]:
    net.add_node(
        node,
        color="blue",
        size=20
    )
    
    if node > 1:
        net.add_edge(node-1,node, dashes=True)

corresp = {}
count = 10

p=1
add_param(p, "/nausf-auth/ue-authentication", "path")
add_param(p, "208950000000031", "imsi")

add_param(p, "IP_AMF", "ip_src")
add_param(p, "IP_AUSF", "ip_dst")

p+=1
add_param(p, "/nudm-ueau/auth-events", "path")
add_param(p, "208950000000031", "imsi")

add_param(p, "IP_AUSF", "ip_src")
add_param(p, "IP_UDM", "ip_dst")

p+=1
add_param(p, "/nudr-dr/subscription-data", "path")
add_param(p, "208950000000031", "imsi")

add_param(p, "IP_UDM", "ip_src")
add_param(p, "IP_UDR", "ip_dst")

# p+=1
# add_param(p, "204 No Content", "status")
# add_param(p, "IP_UDM", "ip_dst")
# add_param(p, "IP_UDR", "ip_src")

# p+=1
# add_param(p, "200 OK", "status")
# add_param(p, "IP_AUSF", "ip_dstc")
# add_param(p, "IP_UDM", "ip_src")

# p+=1
# add_param(p, "200 OK", "status")
# add_param(p, "IP_AMF", "ip_dst")
# add_param(p, "IP_AUSF", "ip_src")

net.set_options("""
var options = {
  "edges": {
    "color": {
      "color": "#444444",
      "highlight": "#444444",
      "hover": "#444444"
    },
    "arrows": {
      "to": { "enabled": true }
    }
  },
  "physics": {
    "barnesHut": {
      "gravitationalConstant": -4000,
      "springLength": 120
    }
  }
}
""")

net.write_html("graph.html")

: 

In [ ]:
from pyvis.network import Network

# Création du graphe
net = Network(
    height="800px",
    width="100%",
    directed=True
)

for node in [1,2,3]:
    net.add_node(
        node,
        color="blue",
        size=20
    )
    
    # if node > 1:
    #     net.add_edge(node-1,node, dashes=True)

corresp = {}
count = 10

p=1
add_param(p, "/nausf-auth/ue-authentication", "path")
add_param(p, "208950000000031", "imsi")
add_param(p, "200 OK", "status")

add_param(p, "IP_AMF", "ip_src")
add_param(p, "IP_AUSF", "ip_dst")

p+=1
add_param(p, "/nudm-ueau/auth-events", "path")
add_param(p, "208950000000031", "imsi")
add_param(p, "200 OK", "status")

add_param(p, "IP_AUSF", "ip_src")
add_param(p, "IP_UDM", "ip_dst")

p+=1
add_param(p, "/nudr-dr/subscription-data", "path")
add_param(p, "208950000000031", "imsi")
add_param(p, "204 No Content", "status")

add_param(p, "IP_UDM", "ip_src")
add_param(p, "IP_UDR", "ip_dst")

net.set_options("""
var options = {
  "edges": {
    "color": {
      "color": "#444444",
      "highlight": "#444444",
      "hover": "#444444"
    },
    "arrows": {
      "to": { "enabled": true }
    }
  },
  "physics": {
    "barnesHut": {
      "gravitationalConstant": -4000,
      "springLength": 120
    }
  }
}
""")

net.write_html("graph2.html")

In [6]:
from pyvis.network import Network

def add_param(central, node_value, edge_value):
    global corresp
    global count 
    
    if node_value not in corresp:
        count += 1
        corresp[node_value] = count
        
        net.add_node(
            count,
            label=node_value,
            color="purple",
            size=20
        )
        curcount = count
    
    curcount = corresp[node_value]
    net.add_edge(central, curcount, label=edge_value)

# Création du graphe
net = Network(
    height="800px",
    width="100%",
    directed=True
)

for node in [1,2,3,4,5,6]:
    net.add_node(
        node,
        color="blue",
        size=20
    )
    
    net.add_node(
        node+10,
        color="red",
        size=20
    )
    
    net.add_edge(node,node+10)
    
    if node > 1:
        net.add_edge(node+10-1,node+10)

corresp = {}
count = 20

p=1
add_param(p, "/nausf-auth/ue-authentication", "path")
add_param(p, "208950000000031", "imsi")

add_param(p, "IP_AMF", "ip_src")
add_param(p, "IP_AUSF", "ip_dst")

p+=1
add_param(p, "/nudm-ueau/auth-events", "path")
add_param(p, "208950000000031", "imsi")

add_param(p, "IP_AUSF", "ip_src")
add_param(p, "IP_UDM", "ip_dst")

p+=1
add_param(p, "/nudr-dr/subscription-data", "path")
add_param(p, "208950000000031", "imsi")

add_param(p, "IP_UDM", "ip_src")
add_param(p, "IP_UDR", "ip_dst")

p+=1
add_param(p, "204 No Content", "status")
add_param(p, "IP_UDM", "ip_dst")
add_param(p, "IP_UDR", "ip_src")

p+=1
add_param(p, "200 OK", "status")
add_param(p, "IP_AUSF", "ip_dstc")
add_param(p, "IP_UDM", "ip_src")

p+=1
add_param(p, "200 OK", "status")
add_param(p, "IP_AMF", "ip_dst")
add_param(p, "IP_AUSF", "ip_src")

net.set_options("""
var options = {
  "edges": {
    "color": {
      "color": "#444444",
      "highlight": "#444444",
      "hover": "#444444"
    },
    "arrows": {
      "to": { "enabled": true }
    }
  },
  "physics": {
    "barnesHut": {
      "gravitationalConstant": -4000,
      "springLength": 120
    }
  }
}
""")

net.write_html("graph.html")

In [5]:
from transformers import AutoTokenizer

# Chargement d'un tokenizer pré-entraîné
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

texts = [
    "source address destination address.",
    "http2 path requester nf type."
]

for text in texts:
    print("\n=== TEXT ===")
    print(text)

    # Tokenisation
    tokens = tokenizer.tokenize(text)
    print("Tokens:", tokens)

    # Conversion en IDs
    ids = tokenizer.convert_tokens_to_ids(tokens)
    print("Token IDs:", ids)

    # (optionnel) version complète avec special tokens
    encoded = tokenizer.encode(text, add_special_tokens=True)
    print("Full encoding (with special tokens):", encoded)


=== TEXT ===
source address destination address.
Tokens: ['source', 'address', 'destination', 'address', '.']
Token IDs: [3120, 4769, 7688, 4769, 1012]
Full encoding (with special tokens): [101, 3120, 4769, 7688, 4769, 1012, 102]

=== TEXT ===
http2 path requester nf type.
Tokens: ['http', '##2', 'path', 'request', '##er', 'n', '##f', 'type', '.']
Token IDs: [8299, 2475, 4130, 5227, 2121, 1050, 2546, 2828, 1012]
Full encoding (with special tokens): [101, 8299, 2475, 4130, 5227, 2121, 1050, 2546, 2828, 1012, 102]


In [6]:
from transformers import AutoTokenizer, AutoModel
import torch

# Modèle BERT
MODEL_NAME = "bert-base-uncased"

# Chargement tokenizer + modèle
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModel.from_pretrained(MODEL_NAME)

# Textes à tester
texts = [
    "source address destination address",
    "http2 path requester nf type"
]

# Désactive les gradients (inférence uniquement)
with torch.no_grad():

    for text in texts:

        print(f"\n==============================")
        print(f"TEXT: {text}")

        # Tokenisation
        inputs = tokenizer(text, return_tensors="pt")

        # Affichage tokens
        tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
        print("Tokens :", tokens)

        # Passage dans BERT
        outputs = model(**inputs)

        # Embeddings des tokens
        token_embeddings = outputs.last_hidden_state[0]

        print("\nToken embeddings shape:")
        print(token_embeddings.shape)

        # Affichage embedding de chaque token
        for token, emb in zip(tokens, token_embeddings):

            print(f"\nTOKEN: {token}")
            print("Embedding (first 10 values):")
            print(emb[:10])

        # Embedding global de la séquence ([CLS])
        cls_embedding = token_embeddings[0]

        print("\n[CLS] embedding (first 10 values):")
        print(cls_embedding[:10])

A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Pl


TEXT: source address destination address
Tokens : ['[CLS]', 'source', 'address', 'destination', 'address', '[SEP]']

Token embeddings shape:
torch.Size([6, 768])

TOKEN: [CLS]
Embedding (first 10 values):
tensor([-0.2648,  0.0269, -0.2158, -0.1172, -0.2225,  0.0673,  0.5195,  0.6488,
         0.0313,  0.0837])

TOKEN: source
Embedding (first 10 values):
tensor([-0.0709,  0.0656,  0.8787, -0.4081,  0.1878, -0.2582, -0.5386,  0.7962,
         0.6421, -0.8503])

TOKEN: address
Embedding (first 10 values):
tensor([-0.3277,  0.2878, -0.1749, -0.2825,  1.3311,  0.2951,  0.0026,  0.2898,
         0.4731, -0.6360])

TOKEN: destination
Embedding (first 10 values):
tensor([-0.2036, -0.7845,  0.9026, -0.5984, -0.1843, -0.0353, -0.1798,  0.7199,
         0.3657, -0.3499])

TOKEN: address
Embedding (first 10 values):
tensor([-0.3798, -0.1959, -0.5115, -0.3180,  1.0923,  0.2507,  0.1077,  0.6706,
         0.1573, -0.6213])

TOKEN: [SEP]
Embedding (first 10 values):
tensor([ 0.7947,  0.1344, -0.2871